from typing import List


def a(word: str) -> str: ...


def capital(string: str) -> str: ...


def join(words: List[str], conj: str = 'and', group: bool = True) -> str: ...


def validate_gender(value: str) -> str: ...


def yesno(value: str) -> bool: ...
