# coding=utf-8

from origin.actions.standard.Activate import Activate
from origin.actions.standard.ChangePassword import ChangePassword
from origin.actions.standard.Clear import Clear
from origin.actions.standard.Combine import Combine
from origin.actions.standard.Deactivate import Deactivate
from origin.actions.standard.Drop import Drop
from origin.actions.standard.Emote import Emote
from origin.actions.standard.Empty import Empty
from origin.actions.standard.Examine import Examine
from origin.actions.standard.Exits import Exits
from origin.actions.standard.Help import Help
from origin.actions.standard.Get import Get
from origin.actions.standard.Give import Give
from origin.actions.standard.Inventory import Inventory
from origin.actions.standard.Locate import Locate
from origin.actions.standard.Look import Look
from origin.actions.standard.Manipulate import Manipulate
from origin.actions.standard.Open import Open
from origin.actions.standard.Pet import Pet
from origin.actions.standard.Put import Put
from origin.actions.standard.Quit import Quit
from origin.actions.standard.Read import Read
from origin.actions.standard.Say import Say
from origin.actions.standard.Show import Show
from origin.actions.standard.Throw import Throw
from origin.actions.standard.Time import Time
from origin.actions.standard.Toggle import Toggle
from origin.actions.standard.Turn import Turn
from origin.actions.standard.Use import Use
from origin.actions.standard.What import What
from origin.actions.standard.Where import Where
from origin.actions.standard.Whisper import Whisper
from origin.actions.standard.Yell import Yell

from origin.actions.sysop.Accounts import Accounts
from origin.actions.sysop.Clean import Clean
from origin.actions.sysop.Destroy import Destroy
from origin.actions.sysop.Dump import Dump
from origin.actions.sysop.Events import Events
from origin.actions.sysop.Force import Force
from origin.actions.sysop.Monitor import Monitor
from origin.actions.sysop.Reload import Reload
from origin.actions.sysop.Relocate import Relocate
from origin.actions.sysop.Return import Return
from origin.actions.sysop.Server import Server
from origin.actions.sysop.Set import Set
from origin.actions.sysop.Subscriptions import Subscriptions
from origin.actions.sysop.Tell import Tell
from origin.actions.sysop.Transport import Transport
from origin.actions.sysop.Verbosity import Verbosity
